name: lignarius

services:

  cadvisor:
    container_name: cadvisor
    image: public.ecr.aws/bitnami/cadvisor:0.52.1-debian-12-r5
    network_mode: "host"
    privileged: true
    ports: [ "9999:8080" ]
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    devices: [ "/dev/kmsg" ]
    profiles: [ cadvisor, monitoring, all ]

  prometheus:
    container_name: prometheus
    image: public.ecr.aws/bitnami/prometheus:3.4.0-debian-12-r1
    network_mode: "host"
    ports: [ "9998:9090" ]
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
    privileged: true
    restart: on-failure
    depends_on: [ cadvisor ]
    profiles: [ prometheus, monitoring, all ]

  grafana:
    container_name: grafana
    image: public.ecr.aws/bitnami/grafana:12.0.0-debian-12-r1
    network_mode: "host"
    ports: [ "9997:3000" ]
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./config/dashboard.json:/var/lib/grafana/dashboards/dashboard.json"
      - "./config/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml"
    privileged: true
    restart: on-failure
    depends_on: [ prometheus ]
    profiles: [ grafana, monitoring, all ]

  postgres:
    container_name: "${POSTGRESQL_DOCKER_NAME-postgres}"
    image: public.ecr.aws/docker/library/postgres:17.5-alpine3.21
    volumes:
      - ./mount/postgres-data:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    restart: always
    env_file:
      - postgres.env
        #    healthcheck:
        #      test: ["CMD", "PGUSER=postgres", "pg_isready"]
        #      interval: 5s
        #      timeout: 3s
        #      retries: 5
    command: ["postgres", "-d", "2", "-c", "log_statement=all", "-c", "log_min_messages=DEBUG2"]
    profiles: [ postgres, postgres-all, all, all-no-ui ]

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports: [ "9001:8999" ]
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_LISTEN_PORT=8999
    restart: on-failure
    depends_on: [ postgres ]
    profiles: [ pgadmin, postgres-all, monitoring, all ]
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-aws}"
    image: public.ecr.aws/localstack/localstack:latest
    ports:
      - "127.0.0.1:8002:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    profiles: [localstack, all-no-ui, all]

  mysql:
    container_name: "${MYSQL_DOCKER_NAME-mysql}"
    image: public.ecr.aws/docker/library/mysql:9.3.0-oraclelinux9
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5
    profiles: [ mysql, all, all-no-ui ]

  redis:
    container_name: "${REDIS_DOCKER_NAME-redis}"
    image: public.ecr.aws/docker/library/redis:8.0.1-alpine3.21
    ports:
      - "8003:6379"
    profiles: [ redis, all, all-no-ui ]

  memcached:
    container_name: "${MEMCACHED_DOCKER_NAME-memcached}"
    image: public.ecr.aws/docker/library/memcached:1.6.38-alpine3.21
    ports:
      - "8004:11211"
    profiles: [ memcached, all, all-no-ui ]

  jenkins:
    container_name: "${JENKINS_DOCKER_NAME-jenkins}"
    image: jenkins/jenkins:lts
    ports:
    - "9002:8081"
    volumes:
      - jenkins_home:/var/jenkins_home
    profiles: [ jenkins, jenkins-all, all-no-ui, all ]

  ssh-agent:
    container_name: "${JENKINS_SSH_AGENT_DOCKER_NAME-ssh-agent}"
    image: jenkins/ssh-agent
    depends_on:
      - jenkins
    profiles: [ ssh-agent, jenkins-all,  all-no-ui, all ]

  allure:
    container_name: "${ALLURE_DOCKER_NAME-allure}"
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "9003:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports
    profiles: [ allure, all-no-ui, all ]

  nginx:
    container_name: "${NGINX_DOCKER_NAME-nginx}"
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8005:8083"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=8083
    profiles: [ nginx, all-no-ui, all ]

  wordpress:
    container_name: "${WORDPRESS_DOCKER_NAME-wordpress}"
    image: wordpress
    restart: always
    ports:
      - "9004:8082"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    profiles: [ wordpress, all-no-ui, all ]

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
    profiles: [ opensearch, all-no-ui, all ]

  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
    profiles: [ opensearch, all-no-ui, all ]

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net
    depends_on: [ opensearch-node1, opensearch-node2 ]
    profiles: [ opensearch, opensearch-all, all ]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    profiles: [ zookeeper, all-no-ui, all ]

  kafka_confluent:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka_confluent
    container_name: kafka_confluent
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zookeeper
    profiles: [ kafka_confluent, kafka_confluent-all, all-no-ui, all ]
    
  kafka:
    #image: public.ecr.aws/bitnami/kafka:4.0.0-debian-12-r5
    image: bitnami/kafka:latest
    hostname: kafka
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LOG4J_ROOT_LOGLEVEL=ERROR # CHECK
      - KAFKA_LOG4J_TOOLS_LOGLEVEL=ERROR # CHECK
    profiles: [ kafka, kafka-no-ui, kafka-all, all-no-ui, all ]
    
  kafka-ui:  # TODO: it exits suddenly
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9005:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092  # TODO check
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
    profiles: [ kafka, kafka-all, all ]

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    profiles: [ mongo, mongo-no-ui, mongo-all, all-no-ui, all ]

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 9006:8084
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    profiles: [ mongo-ui, mongo-all, all ]

  gitea:
    container_name: gitea
    image: gitea/gitea:1.20.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9007:3000"
      - "8006:22"
    profiles: [ gitea, all ]

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9996:9443"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    profiles: [ portainer, all ]

configs:
  pgpass:
    content: postgres:5432:*:postgres:postgres
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "postgres",
        "Host": "postgres",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "postgres",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}

volumes:
  data:
  grafana-data:
  jenkins_home:
  opensearch-data1:
  opensearch-data2:
  wordpress:

networks:
  opensearch-net:
  gitea:
    external: false
