#!/bin/sh

. ./common.sh

print "Bring DOWN the multi-container environment ..."
sleep ${DEMO_SLEEP}
docker compose down --remove-orphans --volumes
print "done bring DOWN the multi-container environment."

